### ISSUE TITLE
Sound volume not saved on restart

### ISSUE THREAD

**Issue by PaulCheffus** [pimoroni/Picade-Sketch#2]
The sound volume always starts at 0 whenever the Picade is restarted either after a reboot or a shutdown. I have tried both versions of the firmware (Picade.hex and Picade_2016.hex) with the same result.

With a pair of headphones plugged in the sound still comes out of the cabinet speakers as well as the headphones.

**Comment by Gadgetoid** [comment]
It's taken me far too long to get around to this. Sorry folks for the delay. However the following is a proposed fix for volume saving which will, once again, happen periodically when volume is adjusted and not just when you forcefully `s`ave configuration via the serial interface.

7f048fbc34a4cb71efc6d43c76a4f924f1fb70e2

Headphone detect should, however, be working, and isn't related to the loss of set volume on reboot.
